language: java
env:
  global:
    - secure: RtXLkitqXEV4X7oSrcSx21QLwbAuvWdiAOt8u4DgSJ8khtFgdjQAwz+VO67hcIsl3oo7SlUPXW8Thbop2qJKx6EezsrxJner0uZUg3K/vKJrjqtq9wvtEcdo9ld3ZQtpmBxwDfg8nh8ieyv0NPHemO4SnquUV8nTsCHOrwEETYL/CxQnRmwK5025/P1HKDAnbsc7nFszzdDb3suSK5Q0oK2jrkICRYayCgWsH+ka0S9DgRhcvX5a90NwjYBWk+4LSVqJ/hg2o/aQs1gTllSXPJWsi2LqxKf1e4A8kYaVhSsMZuU1e2z8FeyMOWFhTUkodiSnX1RcLYtF7gZmuKiYgU3njsHmVy04tJUqkF7o/tlgXCAzIiwmko7ouNefbgt1tqr9mIgOodDy8SCUjeD1LmK9v9bA9v4fXc2Nv7MXM4H2zeTKjogVcvDW7bW9zbMHfD/7NLXglLbUWQE85UubH92/bs9+QC32qICLAqNnuf7pmVXI4PIqYhFmrMBT5g6ysd6HVw9lw+YrmmcCjTnEz16WbKmCXA/7HsyoDS/dPp6UaJXaCUweEQdjq12mCj8oAfWSp5AkiwAlnhgnZ5rLJ89Wozvx3A5XvX84Vb2DyIImy3LCsIaJpKSkTNkw5qsdLp2LLigXRL1yUR2XoWwhLirl1Uucrjd21DbDvEfUiTY=
script:
  - ./gradlew sonarqube
