repositories:
  - name: zalenium
    url: https://raw.githubusercontent.com/zalando/zalenium/master/charts/zalenium

releases:
  - name: zalenium
    namespace: default
    chart: zalenium/zalenium
    values:
      - functional/src/test/resources/values.yml
