logging:
  level:
    root: warn
spring:
  main:
    banner-mode: 'off'
  jackson:
    locale: en_US
    time-zone: Etc/UTC
cucumber:
  slack:
    enabled: false
    icon: https://bit.ly/2wtAjlF
    token: ~
    channel: cucumber
