name: Cucumber
on: push
env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
jobs:
  kubernetes:
    name: Kubernetes features
    runs-on: ubuntu-20.04
    steps:
      - name: Cache minikube files
        uses: actions/cache@v2
        with:
          path: |
            ~/.minikube/cache
          key: ${{ runner.os }}-minikube-cache
          restore-keys: |
            ${{ runner.os }}-minikube-cache
      - name: Start Kubernetes cluster
        uses: hiberbee/github-action-minikube@master
        with:
          profile: cucumber
      - name: Cache Gradle files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Gradle
        run: ./gradlew build
      - name: Test infrastructure features
        run: ./gradlew infrastructure:features
      - name: Test integrational features
        run: ./gradlew integrational:features
      - name: Test common features
        run: ./gradlew common:features
