name: Cucumber Kubernetes
on:
  push:
    branches: [ master ]
env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
jobs:
  cucumber-kubernetes:
    runs-on: ubuntu-latest
    name: Kubernetes features
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Start Kubernetes cluster
        uses: hiberbee/github-action-minikube@master
      - name: Test Kubernetes cluster
        run: kubectl cluster-info
      - name: Test features
        run: ./gradlew kubernetes:features
