name: Kubernetes
on: push
jobs:
  kubernetes:
    runs-on: ubuntu-latest
    name: Kubernetes features
    steps:
      - name: Cache minikube files
        uses: actions/cache@v2
        with:
          path: ~/.minikube/cache
          key: ${{ runner.os }}-minikube-cache
      - name: Start Kubernetes cluster
        uses: hiberbee/github-action-minikube@master
        with:
          profile: cucumber
