on: push
env:
  SNYK_TOKEN: ${{ secrets.snyk }}
jobs:
  scan-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/gradle-jdk11@master
        with:
          args: --severity-threshold=high
