name: Cucumber
on: push
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  kubernetes:
    name: Kubernetes features
    runs-on: ubuntu-latest
    steps:
      - name: Start Kubernetes cluster
        uses: hiberbee/github-action-minikube@master
        with:
          profile: cucumber
      - name: Install Selenium Grid
        run: |
          helm repo add stable https://kubernetes-charts.storage.googleapis.com/
          helm repo update
          helm upgrade --install --cleanup-on-fail --set chrome.enabled=true --set hub.serviceType=NodePort --wait selenium stable/selenium
      - name: Get Selenium Hub service url
        id: selenium-hub-service
        run: echo ::set-output name=url::$(minikube service selenium-selenium-hub --url)
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test Java libraries
        run: ./gradlew test sonarqube
      - name: Cache Gradle files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-
      - name: Test functional features
        run: ./gradlew functional:features
        env:
          HUB_URL: ${{ steps.selenium-hub-service.outputs.url }}
      - name: Test infrastructure features
        run: ./gradlew infrastructure:features
      - name: Test integrational features
        run: ./gradlew integrational:features
      - name: Test common features
        run: ./gradlew common:features
